#!/bin/bash -e
set -e
# Very important for stability and deterministic behaviour:
# keep this exactly in sync with Enigmail's gpgAgent.jsm:resolveGpgPath()
while read _ D ; do
    D=${D%\"\)\;} ; D=${D#\"} ; D=${D%/*}
    [[ ! -d "$D" ]] || PATH="$D:$PATH"
done < <(PATH=/usr/bin:/bin:/usr/sbin:/sbin grep -E "^user_pref\(\"extensions.enigmail.agentPath\"" ../../../prefs.js || : )
export PATH="$PATH:/usr/bin:/usr/local/bin"
exec "$0"-bin "$@"
